// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOdUojLH61EO9Y5fq0csLoKIuHZW8FZM',
    appId: '1:1069169336193:web:1bdc5e9a25c4058cad9280',
    messagingSenderId: '1069169336193',
    projectId: 'notification-50959',
    authDomain: 'notification-50959.firebaseapp.com',
    storageBucket: 'notification-50959.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSaIMLLicjAHjbfwM8xKuuBYMoUP4sVUA',
    appId: '1:1069169336193:android:a9adb2bcc68ca77fad9280',
    messagingSenderId: '1069169336193',
    projectId: 'notification-50959',
    storageBucket: 'notification-50959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD93WNQUweuJH1hIsqWPgmf-clyhMN85Oo',
    appId: '1:1069169336193:ios:8347dba271c41b17ad9280',
    messagingSenderId: '1069169336193',
    projectId: 'notification-50959',
    storageBucket: 'notification-50959.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD93WNQUweuJH1hIsqWPgmf-clyhMN85Oo',
    appId: '1:1069169336193:ios:8347dba271c41b17ad9280',
    messagingSenderId: '1069169336193',
    projectId: 'notification-50959',
    storageBucket: 'notification-50959.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyOdUojLH61EO9Y5fq0csLoKIuHZW8FZM',
    appId: '1:1069169336193:web:6ccdb6f146495801ad9280',
    messagingSenderId: '1069169336193',
    projectId: 'notification-50959',
    authDomain: 'notification-50959.firebaseapp.com',
    storageBucket: 'notification-50959.appspot.com',
  );
}
